{
 "title": "map",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "全国存栏分布",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  sum(`scale`) as value,\n  `lat` as latitude,\n  `lon` as longitude,\n  `province` as name\nFROM companies\ngroup by  `province`\norder by value ASC \n\n\n"
    }
   ]
  },
  {
   "title": "各省今日生猪价格",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  `省份`,\n `外三元`,\n `内三元`,\n `土杂猪`,\nDATE_FORMAT(`日期`,'%Y-%m-%d') as 日期\nFROM PigPrices \nwhere TO_DAYS(`日期`) = TO_DAYS(NOW())\nORDER BY `外三元` DESC\n"
    }
   ]
  },
  {
   "title": "全国生猪均价走势(价格/斤)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "currencyJPY" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(`日期`) AS time,\n  \n  avg(外三元) AS \"外三元\",\n  avg(内三元) AS \"内三元\",\n  avg(土杂猪) AS \"土杂猪\"\n  \nFROM PigPrices\ngroup by `日期`\n"
    }
   ]
  }
 ]
}