services:
  hass:
    image: homeassistant/home-assistant:0.40
    restart: always
    depends_on:
      - influxdb
      - grafana
    links:
      - influxdb
    ports:
      - "8123:8123"
    volumes:
      - /share/Container/home-assistant:/config:rw
      - /etc/localtime:/etc/localtime:ro
  influxdb:
    image: influxdb:1.2-alpine
    restart: always
    volumes:
      - /share/Container/influxdb:/var/lib/influxdb
      - /share/Container/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_GRAPHITE_ENABLED: 'true'
      INFLUXDB_REPORTING_DISABLED: 'true'
  grafana:
    image: grafana/grafana:4.1.2
    restart: always
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - /share/Container/grafana/log:/var/log/grafana
      - /share/Container/grafana/data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
    environment:
      # the login for the web-interface on port 3000 will be admin/secret
      GF_SECURITY_ADMIN_PASSWORD: 'secret'